import React, { useState,useEffect } from 'react';
import Navbar from '../../component/Navbar';
import { useLocation,Link } from 'react-router-dom';
import axios from 'axios';
import Footer from '../../component/Footer';

import { useCart } from '../../CartContext'; // Adjust the path as necessary
import Swal from 'sweetalert2'; // Import SweetAlert
import SecureStorage from 'react-secure-storage';


const CheckoutPage = () => {
  const apiUrl = process.env.REACT_APP_API_URL;
  const [loading, setLoading] = useState(false);

  const { cart } = useCart();
    const location = useLocation();
    const productData = location.state;  // Access the product data from the state
  
   // This will show the product data passed from the previous page
    const [total, setTotalamount] = useState(productData.totalAmount);

  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  // const { userIdentifier } = location.state || {}; // Retrieve userEmail from navigation state

  useEffect(() => {
    const userIdentifier = SecureStorage.getItem('userIdentifier');

    if (userIdentifier) {
      if (userIdentifier.includes('@')) {
        // If the identifier contains '@', it's an email
        setEmail(userIdentifier);
      } else {
        // Otherwise, it's considered a phone number
        setPhone(userIdentifier);
      }
    }
  }, []);
  const [address, setAddress] = useState({
    addressLine1: '',
    addressLine2: '',
    city: '',
    provience: '',
    postalCode: '', 
    country: 'India',
    address_type: 'Home',
     fname:'',
    gst:''

  });
  const [paymentMethod, setPaymentMethod] = useState('online'); // COD for example
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [discountedPrice, setDiscountedPrice] = useState('');
  const [discount, setDiscount] = useState(0);
  const [finalTotal, setFinalTotal] = useState(0); // Initial value set to 0




  
    


  // Form validation for email, phone, and address fields
  const validateForm = () => {
    if (!email || !phone || !address.addressLine1 || !address.city || !address.provience || !address.postalCode || !address.fname) {
      setError('Please fill out all required fields');
      Swal.fire({
        icon: 'error',
        title: 'Validation Error',
        text: 'Please fill out all required fields!',
      });
      return false;
    }
    return true;
  };





  const handleCheckout = async () => {
    setError('');
  
    if (!validateForm()) return;
    setLoading(true);
  
    const payload = {
      email,
      phone,
      totalAmount: total,
      discount: discount,
      paymentMethod,
      address,
      afterdiscount: calculateTotal().toFixed(2),
      items: finalItems.map(item => ({
        productId: item.productId,
              quantity: item.quantity,
              size: item.size || 'N/A', // Default size to N/A if not present
              price: item.price,
              img:item.img,
              title:item.title,
              sku:item.sku
      })),
    };
  
    try {
  
      // Step 1: Create order
      const orderResponse = await fetch(`${apiUrl}orders`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });
  
      if (!orderResponse.ok) {
        const errorDetails = await orderResponse.text();
        throw new Error(`Error creating order: ${errorDetails}`);
      }
  
      const orderData = await orderResponse.json();
    
  
      // Step 2: Initiate Razorpay payment
      const paymentOptions = {
        amount: calculateTotal().toFixed(2) , // Razorpay requires amount in paise
        currency: 'INR',
        order_id: orderData.orderId, // Use the order ID generated by your backend
      };
  
      const { data: razorpayOrder } = await axios.post(`${apiUrl}create-order`, paymentOptions);
  
      const options = {
        key: 'rzp_live_WsL3Pddgbmkywu', // Replace with your Razorpay Key ID
        amount: razorpayOrder.amount,
        currency: razorpayOrder.currency,
        name: 'snaxup',
        description: 'B2B Customize Gift Transaction',
        order_id: razorpayOrder.order_id, // Razorpay Order ID
        handler: async function (response) {
      
  
          // Step 3: After successful payment, update payment status in the database
          const paymentUpdatePayload = {
            orderId: orderData.orderId,
            paymentId: response.razorpay_payment_id,
            status: 'pending',
          };
          const paymentUpdateResponse = await fetch(`${apiUrl}update-order-status`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(paymentUpdatePayload),
          });
  
          if (!paymentUpdateResponse.ok) {
            const errorDetails = await paymentUpdateResponse.text();
            throw new Error(`Error updating payment status: ${errorDetails}`);
          }
  
          // Step 4: Call Shiprocket API to create a shipment
          setLoading(true);
  

             const shiprocketPayload = {
                  order_id: orderData.orderId,
                  order_date: new Date().toISOString(),
                  pickup_location: "Primary",
                  billing_customer_name: address.fname,
                  billing_last_name: email,
                  billing_address: payload.address.addressLine1,
                  billing_city: payload.address.city,
                  billing_pincode: payload.address.postalCode,
                  billing_state: payload.address.provience,
                  billing_country: payload.address.country,
                  billing_email: email,
                  billing_phone: phone,
                  shipping_is_billing: true,
                  order_items: finalItems.map(item => ({  productId: item.productId,
                   

                    name: item.title,
                    sku: item.sku,
                  
                    units: item.quantity,
                    selling_price: item.price,
                    length: 10, // Assuming values
                    breadth: 10,
                    height: 10,
                    weight: 1,
                  })),
                  payment_method: 'Prepaid',
                  sub_total: total,
                  length: 10,
                  breadth: 10,
                  height: 10,
                  weight: 1,
                };

          const shiprocketResponse = await axios.post(`${apiUrl}shiprocket/create-order`, shiprocketPayload);
          if (shiprocketResponse.status === 200) {
            setLoading(false);
            Swal.fire({
              icon: 'success',
              title: 'Order placed successfully!',
              text: 'Your order has been placed and is being processed.',
            });
          } else {
            throw new Error('Failed to create shipment');
          }
        },
        prefill: {
          name: address.fname,
          email: email,
          contact: phone,
        },
        theme: {
          color: '#F37254',
        },
      };
  
      const paymentObject = new window.Razorpay(options);
      paymentObject.open();
    } catch (err) {
      console.error('Error during checkout:', err.message);
  
      // Show error alert if payment fails or order creation fails
      Swal.fire({
        icon: 'error',
        title: 'Payment Failed',
        text: err.message || 'Something went wrong. Please try again.',
      });
  
      setError(err.message || 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };
  
  
// // If productData is an array, map over it directly
const productArray = Array.isArray(productData) 
  ? productData 
  : (productData && typeof productData === 'object' ? Object.values(productData) : []);

  const [couponCode, setCouponCode] = useState(''); // Store the coupon code entered by the user
   
// 1. Extract the numeric-keyed items
const itemsArray = Object.keys(productData)
  .filter(key => !isNaN(key))  // Keep only numeric keys
  .map(key => productData[key]);  // Extract the corresponding product data

// 2. Extract non-numeric product data (assuming only the extra product-related data is required)
const additionalProductData = {
  productId: productData.product_id,
  quantity: 1,  // You can set default quantity or use an actual value if available
  size: 'N/A',  // Default size or use a real size if available
  price: parseFloat(productData.priceBox),  // Using priceBox as the price
  img: productData.img, 
  product_title:productData.product_title // Using img from the direct data
};

// 3. Merge the numeric-keyed items and the additional product data into a single array
const combinedArray = [...itemsArray, additionalProductData];

// 4. Process the array if needed (e.g., formatting the data, etc.)
const finalItems = combinedArray.map(item => {
  const sku = item.product_sku ? item.product_sku : 'box1230';
  

 const title = item.product_title ? item.product_title : 'N/A';
  const sizes = item.actualp_piece ? item.actualp_piece.split(',') : ['N/A'];
  const prices = item.gifts_price  ? item.gifts_price.split(',') : ['N/A'];
  const featureImg = item.product_feature_img || item.img;  // Feature image or img
  
  return {
    productId: item.product_id || item.productId,
    quantity: item.quantity || 1,
    size: sizes[0] || 'N/A',
    price: parseFloat(item.priceBox || item.price || prices[0]),
    img: featureImg || '',
    title : title || '',
    sku: sku || ''
  };
});

// Calculate total whenever cart, paymentMethod, or discount changes
useEffect(() => {
  const totalAmount = calculateTotal(paymentMethod);
  setFinalTotal(totalAmount);
}, [cart, paymentMethod, discount]); // Recalculate total when cart, payment method, or discount changes


   const calculateTotal = (method) => {
    let totalAmount = finalItems.reduce((total, product) => {
      const price = parseFloat(product.price) || 0;
      return total + (price * product.quantity);
    }, 0);
  
    
      totalAmount -= (totalAmount * parseFloat(discount) / 100);
    
  
    // Add ₹30 for COD (if selected)

    return totalAmount;
  };
  
  
   
  // Initial total amount (without coupon)
  const handleApplyCoupon = async () => {
    try {
      const orderAmount = calculateTotal(paymentMethod); // Calculate the total based on selected payment method
      const response = await fetch(`${apiUrl}validate-coupon`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          code: couponCode,
          category: "any",
          orderAmount: orderAmount,
        }),
      });
      const data = await response.json();
  
      if (response.ok) {
        const discountPercentage = data.discount;
        setDiscount(discountPercentage); // Set the discount value in state
        // Recalculate the final amount after applying the discount
        const finalAmount = calculateTotal(paymentMethod);
        setFinalTotal(finalAmount); // Ensure the finalTotal is updated
        Swal.fire({
          title: 'Coupon Applied!',
          text: `You get a ${discountPercentage}% discount. Your final amount is ₹${finalAmount.toFixed(2)}.`,
          icon: 'success',
        });
      } else {
        Swal.fire({
          title: 'Error!',
          text: data.error || 'An unknown error occurred.',
          icon: 'error',
        });
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };
  const initialTotal = calculateTotal();




  

  return (
          <>
          <Navbar/>
          {loading && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <img src="../../img/home/loader.gif" alt="Loading..." className="w-32 h-32" />
        </div>
      )}
    <div className="bg-gray-100 min-h-screen py-10 px-5">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-10">
        
        {/* Left Section - Contact & Delivery */}
        <div className="md:col-span-2 bg-white p-6 rounded-lg shadow-lg">
          <h2 className="text-2xl font-bold mb-6 text-[#8A0404]">Contact</h2>
          <form className="space-y-4">
            
          <div>
            
            <label className="block text-sm font-medium text-gray-600">Email</label>
            <input type="email" className="w-full p-3 border border-gray-300 rounded" placeholder="Email" 
              value={email}
              onChange={(e) => setEmail(e.target.value)}/>
           
          </div>
            <div>
         

      {/* Conditional message based on phone presence */}
      {email ? (
        <p className="text-sm text-green-600 mt-2">Happy shopping!</p>
      ) : (
        <p className="text-sm text-gray-600 mt-2">
          We are using this email to create your account. You will use this email for login.
        </p>
      )}

 
            </div>

            <h2 className="text-2xl font-bold mt-10 mb-6 text-[#8A0404]">Delivery</h2>

            <div>
              <label className="block text-sm font-medium text-gray-600">Country/Region</label>
              <select className="w-full p-3 border border-gray-300 rounded">
                <option>India</option>
              </select>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-600">First name</label>
                <input type="text" className="w-full p-3 border border-gray-300 rounded" placeholder="First name"   onChange={(e) => setAddress({...address, fname:e.target.value})}/>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-600">Last name</label>
                <input type="text" className="w-full p-3 border border-gray-300 rounded" placeholder="Last name" />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-600">Address</label>
              <input type="text" className="w-full p-3 border border-gray-300 rounded" placeholder="Address" 
                                value={address.addressLine1}
                                onChange={(e) => setAddress({ ...address, addressLine1: e.target.value })}
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-600">Apartment, suite, etc. (optional)</label>
              <input type="text" className="w-full p-3 border border-gray-300 rounded" placeholder="Apartment, suite, etc." 
                 onChange={(e) => setAddress({ ...address, addressLine2: e.target.value })}/>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-600">City</label>
                <input type="text" className="w-full p-3 border border-gray-300 rounded" placeholder="City"
                                  onChange={(e) => setAddress({ ...address, city: e.target.value })}
                                  />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-600">State</label>
                <input type="text" className="w-full p-3 border border-gray-300 rounded" placeholder="State"
                                  onChange={(e) => setAddress({ ...address, provience: e.target.value })}
                                  />
                

              </div>
              <div>
                <label className="block text-sm font-medium text-gray-600">PIN code</label>
                <input type="text" className="w-full p-3 border border-gray-300 rounded" placeholder="PIN code"
                                                  onChange={(e) => setAddress({ ...address, postalCode: e.target.value })}

                 />
              </div>

            </div>
            <div>
                <label className="block text-sm font-medium text-gray-600">GST (optional)</label>
                <input type="text" className="w-full p-3 border border-gray-300 rounded" placeholder="GST No."
                                                  onChange={(e) => setAddress({ ...address, gst: e.target.value })}

                 />
              </div>
            <label className="block text-sm font-medium text-gray-600">Phone</label>

            <input
        type="text"
        className="w-full p-3 border border-gray-300 rounded"
        placeholder="Phone"
        value={phone}
        onChange={(e) => setPhone(e.target.value)}
      />
            <div className="flex items-center space-x-2">
              <input type="checkbox" id="text-offers" className="mr-2" />
              <label htmlFor="offers" className="text-sm">Email me with news and offers</label>

              </div>
              
             <div className="flex items-center space-x-2 mt-4">
              <input type="checkbox" id="save" className="mr-2" />
              <label htmlFor="save" className="text-sm">T&C Apply</label>
            </div> 
          </form>
        </div>

        {/* Right Section - Order Summary */}
        <div className="bg-white p-6 rounded-lg shadow-lg">
          <h2 className="text-2xl font-bold mb-6 text-[#8A0404]">Order Summary</h2>
          <div>
          {productArray && productArray.length > 0 ? (
  productArray.map((product, index) => {
    // If product is not an object, skip rendering
    if (typeof product !== 'object') {
      return null;
    }

    // Extract values safely from the product object
    const img = product.product_feature_img
    || product.img;
    const title = product.product_title || product.title;
    const price = product.gifts_price || product.price;
    const size = product.quantity || product.quantity;


    // Render the card only if key fields exist
    if (!img && !title && !price) {
      return null;
    }


    
    return (
      <div key={index} className="flex justify-between items-center border-b pb-4">
        <div className="flex items-center space-x-4">
          {img && <img src={img} alt="product" className="w-20 h-20 object-cover rounded" />}
          <div>
            {title && <p> {title}</p>}
                        <p>Quantity: {product.quantity}</p>
            <p className="text-sm text-gray-600"></p>
          </div>
        </div>
        <p> {price && <p>₹{(parseFloat(price) * (product.quantity || 1)).toFixed(2)}</p>}

            <p className="text-sm text-gray-900 line-through">MRP: ₹{product.product_price ? product.product_price.split(',')[0] : 'N/A'}</p>

</p>
      </div>
    );
  })
) : null}

    </div>

  

<div
           className="flex items-center space-x-4">
{productData?.img && (
  // Parse the productData.img string to get the first image
  <img 
    src={JSON.parse(productData.img)[0]} // Get the first image from the parsed array
    alt={productData.product_title} 
    className="w-20 h-20 object-cover rounded" 
  />
)}
              <div>
              
              <p>      {productData?.product_title && <p> {productData.product_title}</p>}

</p>
                <p>      {productData?.priceBox && <p>Price: {productData.priceBox}</p>}

                </p>
              </div>
            </div>
          

          <div>
          <div className="mt-4">
            <label className="block text-sm font-medium text-gray-600">Discount code</label>
            <div className="flex space-x-4 mt-2">
              <input type="text"    value={couponCode}                       // Bind the input value to the state
          onChange={(e) => setCouponCode(e.target.value)}  className="w-full p-3 border border-orange-600 rounded " placeholder="Discount code" />
              <button onClick={handleApplyCoupon} className="hover:bg-orange-600 hover:text-white bg-white text-black py-2 px-8 rounded-full text-lg border border-orange-600 transition duration-300">Apply</button>
            </div>
          </div>
      <div className="mt-6 border-t pt-4">
        <div className="flex justify-between items-center">
          <p>Subtotal </p>
          <p>₹{calculateTotal().toFixed(2)}</p>
        </div>
        <div className="flex justify-between items-center mt-4">
            <p>Shipping</p>
            <p className='text-green-600 '>FREE</p>
          </div>
        {discount ? (
  <p className="text-green-600 font-semibold">You saved Rs. {discount}!</p>
) : null}      </div>

 
    <div className="mt-6 border-t pt-4 text-center">
      
<div>
          <div className="mt-6 border-t pt-4">
         
            <p className="mt-2 text-gray-600">Enter shipping address</p>
          </div>

          <div className="mt-6 border-t pt-4">
            <div className="flex justify-between items-center font-bold text-lg">
              <p className='text-[#8A0404]'>Total</p>
           
             <p> {calculateTotal() > 0 ? ` ₹${calculateTotal().toFixed(2)}` : ' No amount due'}
                
              <p className="text-sm text-gray-500">
  (Incl. of all taxes)
</p>
</p>
            </div>
          </div>
          </div>

    </div>
  
</div>

          <button
                type="button"
                onClick={handleCheckout}
                className="w-full bg-orange-600 text-white p-3 rounded mt-4"
              >
                Place Order
              </button>
        </div>
      </div>
    </div>
    <Footer/>
    </>
  );
};

export default CheckoutPage;
